import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AudioProvider, { AudioPlayerContext } from '@/app/src/components/AudioPlayerContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'kr1st0 beatz',
  description: 'Generated by kristo!',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AudioProvider>
          {children}
        </AudioProvider>
      </body>
    </html>
  )
}
